name: experiment_sdk_flutter
description: Experiment SDK for Flutter powered by ProductMinds. Amplitude Experiment is a tool to manage and orchestrate AB testing and feature flagging. 
version: 2.0.0
homepage: https://github.com/productminds/experiment_sdk_flutter

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: 3.32.0

dependencies:
  amplitude_flutter: ^4.3.2
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
